[2024-07-31T16:56:37.257+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T16:56:37.267+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie.throw.err scheduled__2024-07-29T02:10:00+00:00 [queued]>
[2024-07-31T16:56:37.270+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie.throw.err scheduled__2024-07-29T02:10:00+00:00 [queued]>
[2024-07-31T16:56:37.271+0900] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-07-31T16:56:37.276+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): throw.err> on 2024-07-29 02:10:00+00:00
[2024-07-31T16:56:37.279+0900] {standard_task_runner.py:64} INFO - Started process 20802 to run task
[2024-07-31T16:56:37.282+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'movie', 'throw.err', 'scheduled__2024-07-29T02:10:00+00:00', '--job-id', '875', '--raw', '--subdir', 'DAGS_FOLDER/movie.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmpjh90yeg9']
[2024-07-31T16:56:37.283+0900] {standard_task_runner.py:91} INFO - Job 875: Subtask throw.err
[2024-07-31T16:56:37.297+0900] {task_command.py:426} INFO - Running <TaskInstance: movie.throw.err scheduled__2024-07-29T02:10:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-31T16:56:37.317+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie' AIRFLOW_CTX_TASK_ID='throw.err' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-29T02:10:00+00:00'
[2024-07-31T16:56:37.318+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T16:56:37.323+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-31T16:56:37.324+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-31T16:56:37.326+0900] {subprocess.py:86} INFO - Output:
[2024-07-31T16:56:37.328+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-31T16:56:37.328+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T16:56:37.331+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-31T16:56:37.333+0900] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=movie, task_id=throw.err, run_id=scheduled__2024-07-29T02:10:00+00:00, execution_date=20240729T021000, start_date=20240731T075637, end_date=20240731T075637
[2024-07-31T16:56:37.336+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 875 for task throw.err (Bash command failed. The command returned a non-zero exit code 1.; 20802)
[2024-07-31T16:56:37.355+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-31T16:56:37.362+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-31T16:56:37.362+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
