[2024-07-31T16:49:01.578+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T16:49:01.589+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie.throw.err scheduled__2024-07-25T02:10:00+00:00 [queued]>
[2024-07-31T16:49:01.592+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie.throw.err scheduled__2024-07-25T02:10:00+00:00 [queued]>
[2024-07-31T16:49:01.592+0900] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-07-31T16:49:01.598+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): throw.err> on 2024-07-25 02:10:00+00:00
[2024-07-31T16:49:01.601+0900] {standard_task_runner.py:64} INFO - Started process 20360 to run task
[2024-07-31T16:49:01.603+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'movie', 'throw.err', 'scheduled__2024-07-25T02:10:00+00:00', '--job-id', '853', '--raw', '--subdir', 'DAGS_FOLDER/movie.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmppwnj7qm3']
[2024-07-31T16:49:01.605+0900] {standard_task_runner.py:91} INFO - Job 853: Subtask throw.err
[2024-07-31T16:49:01.619+0900] {task_command.py:426} INFO - Running <TaskInstance: movie.throw.err scheduled__2024-07-25T02:10:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-31T16:49:01.639+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie' AIRFLOW_CTX_TASK_ID='throw.err' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T02:10:00+00:00'
[2024-07-31T16:49:01.640+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T16:49:01.647+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-31T16:49:01.648+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-31T16:49:01.650+0900] {subprocess.py:86} INFO - Output:
[2024-07-31T16:49:01.654+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-31T16:49:01.654+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T16:49:01.657+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-31T16:49:01.660+0900] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=movie, task_id=throw.err, run_id=scheduled__2024-07-25T02:10:00+00:00, execution_date=20240725T021000, start_date=20240731T074901, end_date=20240731T074901
[2024-07-31T16:49:01.663+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 853 for task throw.err (Bash command failed. The command returned a non-zero exit code 1.; 20360)
[2024-07-31T16:49:01.665+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-31T16:49:01.672+0900] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-31T16:49:01.673+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
