[2024-07-24T15:07:12.052+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T15:07:12.059+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_db.Check scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-24T15:07:12.061+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_db.Check scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-24T15:07:12.061+0900] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-07-24T15:07:12.065+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Check> on 2024-07-18 00:00:00+00:00
[2024-07-24T15:07:12.067+0900] {standard_task_runner.py:64} INFO - Started process 94393 to run task
[2024-07-24T15:07:12.070+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_db', 'Check', 'scheduled__2024-07-18T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/import_db.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmpt19vkji2']
[2024-07-24T15:07:12.071+0900] {standard_task_runner.py:91} INFO - Job 251: Subtask Check
[2024-07-24T15:07:12.084+0900] {task_command.py:426} INFO - Running <TaskInstance: import_db.Check scheduled__2024-07-18T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T15:07:12.108+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_db' AIRFLOW_CTX_TASK_ID='Check' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-18T00:00:00+00:00'
[2024-07-24T15:07:12.108+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T15:07:12.114+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T15:07:12.114+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /Users/DE32/airflow/sh/simple_done_check.sh ~/data/done/20240718/_DONE']
[2024-07-24T15:07:12.117+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T15:07:12.120+0900] {subprocess.py:93} INFO - _DONE Path = /Users/DE32/data/done/20240718/_DONE
[2024-07-24T15:07:12.120+0900] {subprocess.py:93} INFO - /Users/DE32/airflow/sh/simple_done_check.sh: line 7: figlet: command not found
[2024-07-24T15:07:12.121+0900] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T15:07:12.121+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T15:07:12.127+0900] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_db, task_id=Check, run_id=scheduled__2024-07-18T00:00:00+00:00, execution_date=20240718T000000, start_date=20240724T060712, end_date=20240724T060712
[2024-07-24T15:07:12.132+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T15:07:12.140+0900] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T15:07:12.141+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
