[2024-07-24T16:26:32.514+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T16:26:32.522+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: make_parquet.to.parquet scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-24T16:26:32.524+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: make_parquet.to.parquet scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-24T16:26:32.524+0900] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-07-24T16:26:32.528+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): to.parquet> on 2024-07-15 00:00:00+00:00
[2024-07-24T16:26:32.531+0900] {standard_task_runner.py:64} INFO - Started process 99624 to run task
[2024-07-24T16:26:32.533+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'make_parquet', 'to.parquet', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/make_parquet.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmpdma8ixte']
[2024-07-24T16:26:32.534+0900] {standard_task_runner.py:91} INFO - Job 449: Subtask to.parquet
[2024-07-24T16:26:32.549+0900] {task_command.py:426} INFO - Running <TaskInstance: make_parquet.to.parquet scheduled__2024-07-15T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T16:26:32.571+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='make_parquet' AIRFLOW_CTX_TASK_ID='to.parquet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-24T16:26:32.571+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T16:26:32.577+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T16:26:32.577+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        echo "to.parquet"\n\n        READ_PATH=~/data/csv/20240715/csv.csv\n        SAVE_PATH=~/data/parquet/20240715/parquet.parquet\n\n        mkdir -p $SAVE_PATH\n\n        python ~/airflow/operator/csv2parquet.py $READ_PATH $SAVE_PATH\n        ']
[2024-07-24T16:26:32.580+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T16:26:32.581+0900] {subprocess.py:93} INFO - to.parquet
[2024-07-24T16:26:32.796+0900] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-07-24T16:26:32.796+0900] {subprocess.py:93} INFO -   File "/Users/DE32/airflow/operator/csv2parquet.py", line 7, in <module>
[2024-07-24T16:26:32.796+0900] {subprocess.py:93} INFO -     df = pd.read_csv(READ_PATH,
[2024-07-24T16:26:32.796+0900] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^
[2024-07-24T16:26:32.797+0900] {subprocess.py:93} INFO -   File "/Users/DE32/.pyenv/versions/note/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
[2024-07-24T16:26:32.797+0900] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2024-07-24T16:26:32.797+0900] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-24T16:26:32.797+0900] {subprocess.py:93} INFO -   File "/Users/DE32/.pyenv/versions/note/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
[2024-07-24T16:26:32.797+0900] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2024-07-24T16:26:32.797+0900] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-24T16:26:32.797+0900] {subprocess.py:93} INFO -   File "/Users/DE32/.pyenv/versions/note/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
[2024-07-24T16:26:32.798+0900] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2024-07-24T16:26:32.798+0900] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-24T16:26:32.798+0900] {subprocess.py:93} INFO -   File "/Users/DE32/.pyenv/versions/note/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
[2024-07-24T16:26:32.798+0900] {subprocess.py:93} INFO -     return mapping[engine](f, **self.options)
[2024-07-24T16:26:32.798+0900] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-24T16:26:32.798+0900] {subprocess.py:93} INFO -   File "/Users/DE32/.pyenv/versions/note/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
[2024-07-24T16:26:32.798+0900] {subprocess.py:93} INFO -     self._reader = parsers.TextReader(src, **kwds)
[2024-07-24T16:26:32.799+0900] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-24T16:26:32.799+0900] {subprocess.py:93} INFO -   File "parsers.pyx", line 574, in pandas._libs.parsers.TextReader.__cinit__
[2024-07-24T16:26:32.799+0900] {subprocess.py:93} INFO -   File "parsers.pyx", line 766, in pandas._libs.parsers.TextReader._get_header
[2024-07-24T16:26:32.799+0900] {subprocess.py:93} INFO -   File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
[2024-07-24T16:26:32.799+0900] {subprocess.py:93} INFO -   File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
[2024-07-24T16:26:32.799+0900] {subprocess.py:93} INFO -   File "parsers.pyx", line 2053, in pandas._libs.parsers.raise_parser_error
[2024-07-24T16:26:32.799+0900] {subprocess.py:93} INFO - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 2823: invalid start byte
[2024-07-24T16:26:32.827+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T16:26:32.828+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T16:26:32.831+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T16:26:32.833+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=make_parquet, task_id=to.parquet, run_id=scheduled__2024-07-15T00:00:00+00:00, execution_date=20240715T000000, start_date=20240724T072632, end_date=20240724T072632
[2024-07-24T16:26:32.836+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 449 for task to.parquet (Bash command failed. The command returned a non-zero exit code 1.; 99624)
[2024-07-24T16:26:32.860+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T16:26:32.865+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T16:26:32.866+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
